from .neumf import NeuMF
from .generalized_mf import GeneralizedMF
from .NFM import NFM
from .DeepFM import DeepFM
from .DMF import DMF
from .NAIS import NAIS
from .UserAutoRec import UserAutoRec
from .ItemAutoRec import ItemAutoRec
from .ConvNeuMF import ConvNeuMF
from .WideAndDeep import WideAndDeep
from .ConvMF import ConvMF
from .NPR import NPR
