experiment:
  dataset: movielens_20m
  data_config:
    strategy: dataset
    header: True
    dataset_path: ../data/movielens_20m/dataset.tsv
  splitting:
#    save_on_disk: True
#    save_folder: ../data/movielens_20m/splitting
    test_splitting:
      strategy: temporal_holdout
      test_ratio: 0.2
  top_k: 100
  evaluation:
    simple_metrics: [ nDCG, HR ]
  gpu: -1
  models:
    NeuMF:
      embed_mf_size: 10
      embed_mlp_size: 10
      mlp_hidden_sizes: (64,32)
      dropout: 0.0
      is_mf_train: True
      is_mlp_train: True
      learning_rate: 0.00001
      lambda_weights: 0.1
      m: 0
      epochs: 1
      batch_size: 2048
      batch_eval_items: 128
