experiment:
  dataset: movielens_20m
  data_config:
    strategy: dataset
    header: True
    dataset_path: ../data/movielens_20m/dataset.tsv
  splitting:
#    save_on_disk: True
#    save_folder: ../data/movielens_20m/splitting
    test_splitting:
      strategy: temporal_holdout
      test_ratio: 0.2
  top_k: 100
  evaluation:
    simple_metrics: [ nDCG, HR ]
  gpu: -1
  models:
    LightGCN:
      lr: 0.001
      epochs: 1
      factors: 10
      batch_size: 4096
      l_w: 1e-6
      n_layers: 2
