experiment:
  dataset: last-fm
  data_config:
#    strategy: dataset
#    dataset_path: ../data/{0}/dataset.txt
    strategy: fixed
    train_path: ../data/{0}/train.txt
    test_path: ../data/{0}/test.txt
    side_information:
      - dataloader: KGINLoader
        attributes: ../data/{0}/kg_final.txt
#  prefiltering:
#    strategy: iterative_k_core
#    core: 5
  splitting:
    test_splitting:
      strategy: random_subsampling
      test_ratio: 0.2
  top_k: 10
  gpu: -1
  external_models_path: ../external/models/__init__.py
  evaluation:
    cutoffs: [10]
    simple_metrics: [nDCGRendle2020, nDCG, HR, Precision, Recall, MAP, MRR, ItemCoverage, UserCoverage, NumRetrieved, UserCoverage, Gini, SEntropy, EFD, EPC]
  models:
    KGIN:
      meta:
        verbose: True
        validation_rate: 10
        save_recs: False
        save_weights: False
        restore: False
      seed: 42
      lr: [0.1, 0.01, 0.001, 0.0001]
      epochs: 20
      batch_size: 16
      embedding: [1,5,100]
      first_order_limit: [3]
      second_order_limit: [3]
      loader: KGINLoader
