experiment:
  dataset: movielens_1m
  data_config:
    strategy: dataset
    dataset_path: ../data/movielens_1m/dataset.tsv
  splitting:
    test_splitting:
        strategy: random_subsampling
        test_ratio: 0.2
  top_k: 50
  evaluation:
    cutoffs: 50
    simple_metrics: [HR, nDCG, EFD, ACLT, APLT]
    paired_ttest: True
    wilcoxon_test: True
  gpu: 0
  models:
    AMF:
      meta:
        save_recs: False
        hyper_max_evals: 5
        hyper_opt_alg: tpe
        eval_perturbations: True
        validation_rate: 1
      epochs: 2
      batch_size: 256
      factors: 10 # [quniform, 50, 100, 1]
      lr: 0.001 # [loguniform, -2, -1]
      l_w: 0.0001
      l_b: 0.0001
      eps: 0.5 # [uniform, 0.1, 0.5] # Magnitude of the Perturbation
      l_adv: 1 # Adversarial Regularization Parameters
      adversarial_epochs: 1 # [quniform, 4, 8, 1] # Number of final epochs to be run [APR starts from (epochs - adversarial_epochs) epoch]
      eps_iter: 0.0625 # 2.5 * Îµ-test / num_steps (Iterative Perturbations)
      nb_iter: 20  #Number of Iterative Perturbations (MSAP, Flairs '21)