experiment:
  dataset: movielens_1m_v030
  # Optional W&B integration: leave absent (or commented) to disable.
  wandb:
     project: "Elliot-experiments"
     api_key: "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"
     run_name: "movielens-debug"
  device: cpu
  data_config:
    strategy: hierarchy
    data_folder: ../data/{0}/splitting
  top_k: 20
  evaluation:
    simple_metrics: [nDCG, HR]
  models:
    ItemKNN:
      meta:
        save_recs: False
      neighborhood: 500
      similarity: rp3beta
      alpha: 1.0
      beta: 0.6
      normalize_similarity: True
      eval_batch_size: 2048
#    RecommendationFolder:
#      folder: ../results/{0}/recs
#      reader:
#        ext: [".tsv", ".csv"]
#        header: True
#    RP3beta:
#      meta:
#        save_recs: False
#      neighborhood: 500
#      normalize_similarity: True
#      alpha: 1.0
#      beta: 0.6
#    EASER:
#      meta:
#        save_recs: False
#      batch_size: 2048
#      l2_norm: 1000
#    PureSVD:
#      meta:
#        save_recs: False
#      batch_size: 4096
#    MF2020Batch:
#      meta:
#        save_recs: False
#      m: 1
#      batch_size: 2048
    BPRMFBatch:
      meta:
        save_recs: False
      batch_size: 2048
      eval_batch_size: 512
#    SVDpp:
#      meta:
#        save_recs: False
#      batch_size: 2048
#    FunkSVD:
#      meta:
#        save_recs: False
#        validation_rate: 10
#      batch_size: 4096
#      epochs: 40
#        save_weights: True
#        restore: True
#      epochs: 1
#      factors: 10
#      lr: 0.001
#      reg: 0.0025
